vich_uploader:
    db_driver: orm

    mappings:
        archive:
            uri_prefix: /archive
            upload_destination: '%kernel.project_dir%/public/archives'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
